name: shortlink-dev
services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/shortlink
    depends_on:
      - db
    ports:
      - "8080:8080"
    develop:
      watch:
        - path: ./backend
          action: rebuild
        - path: ./frontend
          action: rebuild

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: shortlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
